version: '3.8'
services:
  bitcoind:
    image: ruimarinho/bitcoin-core:0.21.0
    command:
      -printtoconsole=1
      -regtest=1
    ports:
      - "18443:18443"
    volumes:
      - bitcoin_data:/home/bitcoin/.bitcoin
    environment:
      BITCOIN_EXTRA_ARGS: |
        server=1
        rpcallowip=0.0.0.0/0
        rpcuser=${BITCOIN_RPC_USER}
        rpcpassword=${BITCOIN_RPC_PASSWORD}
        rpcport=18443

volumes:
  bitcoin_data:
